import {
  existsSync,
  mkdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";

import type { CliOutput } from "@/cli";
import { isCompiledBinary } from "@/version";

export const SYSTEMD_UNIT = "phi.service";
export const LAUNCHD_LABEL = "app.phi.server";

const DEFAULT_HOST = "127.0.0.1";
const DEFAULT_PORT = "3141";
const BAKED_ENV_KEYS = ["PHI_HOST", "PHI_PORT", "PHI_ROOT"] as const;
const FILE_LIMIT = 8192;

interface CommandResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

export interface ServiceDependencies {
  env?: NodeJS.ProcessEnv;
  platform?: NodeJS.Platform;
  uid?: number;
  username?: string;
  home?: string;
  execPath?: string;
  compiled?: boolean;
  cliPath?: string;
  which?: typeof Bun.which;
  runCommand?: (args: string[]) => Promise<CommandResult>;
}

export interface ServiceUnitInput {
  programArguments: readonly string[];
  workingDirectory: string;
  environment: Record<string, string>;
  logPath?: string;
}

export interface ServiceStatus {
  running: boolean;
  pid: number;
  state: string;
  failed: boolean;
}

const serviceHelp = `Usage: phi service <command>

Install Phi as a user-level background service (systemd on Linux, launchd
on macOS). It runs as your user, keeps data in ~/.phi, and restarts on
crash. Re-running install overwrites the service definition.

Commands:
  install [--linger]  Write the definition, enable it, and start the service
  uninstall           Stop the service and remove its definition
  start               Start the service
  stop                Stop the service
  restart             Restart the service
  status              Show whether the service is running

On Linux, --linger starts the service at boot without logging in.
`;

async function defaultRunCommand(args: string[]): Promise<CommandResult> {
  const child = Bun.spawn(args, { stdin: "ignore", stdout: "pipe", stderr: "pipe" });
  const [exitCode, stdout, stderr] = await Promise.all([
    child.exited,
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ]);
  return { exitCode, stdout, stderr };
}

function requireBinary(which: typeof Bun.which, name: string): string {
  const path = which(name);
  if (!path) throw new Error(`${name} was not found`);
  return path;
}

function xmlEscape(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function systemdSafeUnquoted(value: string): boolean {
  return /^[A-Za-z0-9_./:+@=-]+$/.test(value);
}

function systemdQuote(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/** Escape `%` specifiers in non-Exec values. `$` is literal here. */
export function systemdDirectiveValue(value: string): string {
  const escaped = value.replaceAll("%", "%%");
  if (systemdSafeUnquoted(value) && !value.includes("%")) return value;
  return systemdQuote(escaped);
}

/** Escape one ExecStart word: `$$` for `$`, `%%` for `%`. */
export function systemdExecArg(value: string): string {
  // String#replace treats `$$` in the replacement as a single `$`.
  const escaped = value.replaceAll("%", "%%").replaceAll("$", () => "$$");
  if (systemdSafeUnquoted(value) && !value.includes("%") && !value.includes("$")) {
    return value;
  }
  return systemdQuote(escaped);
}

export function renderSystemdUnit(input: ServiceUnitInput): string {
  const environment = Object.entries(input.environment)
    .map(([key, value]) => {
      const assignment = `${key}=${value.replaceAll("%", "%%")}`;
      return `Environment=${systemdQuote(assignment)}`;
    })
    .join("\n");
  return [
    "# Generated by phi service install. Re-running install overwrites this file.",
    "[Unit]",
    "Description=Phi server",
    "StartLimitIntervalSec=60",
    "StartLimitBurst=5",
    "",
    "[Service]",
    "Type=exec",
    `WorkingDirectory=${systemdDirectiveValue(input.workingDirectory)}`,
    `ExecStart=${input.programArguments.map(systemdExecArg).join(" ")}`,
    "Restart=on-failure",
    "RestartSec=3",
    "TimeoutStopSec=30",
    `LimitNOFILE=${FILE_LIMIT}`,
    environment,
    "",
    "[Install]",
    "WantedBy=default.target",
    "",
  ].join("\n");
}

export function renderLaunchdPlist(input: ServiceUnitInput): string {
  const argumentsXml = input.programArguments
    .map((argument) => `      <string>${xmlEscape(argument)}</string>`)
    .join("\n");
  const environmentXml = Object.entries(input.environment)
    .map(
      ([key, value]) =>
        `      <key>${xmlEscape(key)}</key>\n      <string>${xmlEscape(value)}</string>`,
    )
    .join("\n");
  const logPath = input.logPath ?? "";
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>${xmlEscape(LAUNCHD_LABEL)}</string>
    <key>ProgramArguments</key>
    <array>
${argumentsXml}
    </array>
    <key>WorkingDirectory</key>
    <string>${xmlEscape(input.workingDirectory)}</string>
    <key>EnvironmentVariables</key>
    <dict>
${environmentXml}
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>ProcessType</key>
    <string>Background</string>
    <key>SoftResourceLimits</key>
    <dict>
      <key>NumberOfFiles</key>
      <integer>${FILE_LIMIT}</integer>
    </dict>
    <key>ExitTimeOut</key>
    <integer>30</integer>
    <key>StandardOutPath</key>
    <string>${xmlEscape(logPath)}</string>
    <key>StandardErrorPath</key>
    <string>${xmlEscape(logPath)}</string>
  </dict>
</plist>
`;
}

export function parseSystemctlShow(stdout: string): ServiceStatus {
  const value = (key: string) =>
    stdout.match(new RegExp(`^${key}=(.*)$`, "m"))?.[1]?.trim() ?? "";
  const state = value("ActiveState");
  const pid = Number(value("MainPID") || "0");
  return {
    running: state === "active",
    pid: Number.isInteger(pid) && pid > 0 ? pid : 0,
    state,
    failed: state === "failed",
  };
}

export function parseLaunchctlPrint(stdout: string): ServiceStatus {
  const state = stdout.match(/^\s*state = (\S+)/m)?.[1] ?? "";
  const pid = Number(stdout.match(/^\s*pid = (\d+)/m)?.[1] || "0");
  const running = state === "running" || pid > 0;
  return {
    running,
    pid: Number.isInteger(pid) && pid > 0 ? pid : 0,
    state,
    failed: state === "spawn failed" || state === "failed",
  };
}

export function isLaunchctlMissing(result: {
  exitCode: number;
  stdout: string;
  stderr: string;
}): boolean {
  if (result.exitCode === 0) return false;
  const text = `${result.stdout}\n${result.stderr}`;
  return /no such process/i.test(text)
    || /could not find specified service/i.test(text)
    || /could not find service "/i.test(text);
}

export function isLaunchctlDomainMissing(result: {
  exitCode: number;
  stdout: string;
  stderr: string;
}): boolean {
  if (result.exitCode === 0) return false;
  return /could not find domain|could not print domain/i
    .test(`${result.stdout}\n${result.stderr}`)
    || isLaunchctlMissing(result);
}

function launchctlCommandError(
  command: string[],
  result: { exitCode: number; stdout: string; stderr: string },
): Error {
  const detail =
    result.stderr.trim() || result.stdout.trim() || `exit ${result.exitCode}`;
  return new Error(`\`${command.join(" ")}\` failed: ${detail}`);
}

export function listenUrl(env: NodeJS.ProcessEnv = process.env): string {
  const host = env.PHI_HOST?.trim() || DEFAULT_HOST;
  const port = env.PHI_PORT?.trim() || DEFAULT_PORT;
  return `http://${host}:${port}`;
}

export function serveProgramArguments(options: {
  compiled: boolean;
  execPath: string;
  cliPath: string;
}): string[] {
  const execPath = resolve(options.execPath);
  if (options.compiled) return [execPath, "serve"];
  return [execPath, resolve(options.cliPath), "serve"];
}

function servicePath(env: NodeJS.ProcessEnv, execPath: string): string {
  const extra = dirname(resolve(execPath));
  const current = env.PATH?.trim();
  const fallback = [
    extra,
    "/opt/homebrew/bin",
    "/usr/local/bin",
    join(env.HOME ?? homedir(), ".local/bin"),
    "/usr/bin",
    "/bin",
  ];
  const parts = (current ? current.split(":") : fallback).filter(Boolean);
  if (!parts.includes(extra)) parts.unshift(extra);
  return parts.join(":");
}

function bakedEnvironment(
  env: NodeJS.ProcessEnv,
  execPath: string,
): Record<string, string> {
  const environment: Record<string, string> = {
    PATH: servicePath(env, execPath),
  };
  for (const key of BAKED_ENV_KEYS) {
    const value = env[key]?.trim();
    if (value) environment[key] = value;
  }
  return environment;
}

function dataRoot(home: string, env: NodeJS.ProcessEnv): string {
  return env.PHI_ROOT ?? join(home, ".phi");
}

function definitionPath(
  platform: "linux" | "darwin",
  home: string,
  env: NodeJS.ProcessEnv,
): string {
  if (platform === "linux") {
    const configHome = env.XDG_CONFIG_HOME?.trim() || join(home, ".config");
    return join(configHome, "systemd/user", SYSTEMD_UNIT);
  }
  return join(home, "Library/LaunchAgents", `${LAUNCHD_LABEL}.plist`);
}

function unitInput(
  platform: "linux" | "darwin",
  home: string,
  env: NodeJS.ProcessEnv,
  programArguments: readonly string[],
  execPath: string,
): ServiceUnitInput {
  return {
    programArguments,
    workingDirectory: home,
    environment: bakedEnvironment(env, execPath),
    ...(platform === "darwin"
      ? { logPath: join(dataRoot(home, env), "logs", "server.log") }
      : {}),
  };
}

function writeDefinition(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, { encoding: "utf8", mode: 0o644 });
}

function notInstalledError(): Error {
  return new Error("Phi service is not installed. Run `phi service install`.");
}

export async function runService(
  output: CliOutput,
  args: readonly string[],
  dependencies: ServiceDependencies = {},
): Promise<number> {
  const env = dependencies.env ?? process.env;
  const [subcommand = "help", ...rest] = args;
  if (
    subcommand === "help" ||
    subcommand === "--help" ||
    subcommand === "-h"
  ) {
    output.stdout(serviceHelp);
    return 0;
  }
  if (env.PHI_IN_SANDBOX === "1") {
    throw new Error("service commands cannot run inside a Phi sandbox");
  }

  const platform = dependencies.platform ?? process.platform;
  if (platform !== "linux" && platform !== "darwin") {
    throw new Error("phi service is only supported on macOS and Linux");
  }

  let linger = false;
  if (subcommand === "install") {
    for (const argument of rest) {
      if (argument === "--linger") linger = true;
      else throw new Error("Usage: phi service install [--linger]");
    }
  } else if (rest.length > 0) {
    throw new Error(`Usage: phi service ${subcommand}`);
  }
  if (linger && platform !== "linux") {
    throw new Error("--linger is only supported on Linux");
  }

  const which = dependencies.which ?? Bun.which;
  const runner = dependencies.runCommand ?? defaultRunCommand;
  const home = dependencies.home ?? env.HOME ?? homedir();
  const execPath = dependencies.execPath ?? process.execPath;
  const compiled = dependencies.compiled ?? isCompiledBinary(execPath);
  const cliPath = dependencies.cliPath ?? "";
  if (!compiled && !cliPath) {
    throw new Error("source checkouts need the Phi CLI entry path");
  }
  const programArguments = serveProgramArguments({ compiled, execPath, cliPath });
  const path = definitionPath(platform, home, env);
  const input = unitInput(platform, home, env, programArguments, execPath);
  const contents =
    platform === "linux" ? renderSystemdUnit(input) : renderLaunchdPlist(input);

  const run = async (command: string[], allowFailure = false) => {
    const result = await runner(command);
    if (result.exitCode !== 0 && !allowFailure) {
      const detail =
        result.stderr.trim() || result.stdout.trim() || `exit ${result.exitCode}`;
      throw new Error(`\`${command.join(" ")}\` failed: ${detail}`);
    }
    return result;
  };

  if (platform === "linux") {
    const systemctl = requireBinary(which, "systemctl");
    const unit = SYSTEMD_UNIT;
    const requireInstalled = () => {
      if (!existsSync(path)) throw notInstalledError();
    };

    if (subcommand === "install") {
      writeDefinition(path, contents);
      await run([systemctl, "--user", "daemon-reload"]);
      await run([systemctl, "--user", "enable", unit]);
      await run([systemctl, "--user", "restart", unit]);
      output.stdout(`Installed and started the Phi service (${path}).\n`);
      output.stdout(`Open ${listenUrl(env)}\n`);
      const username =
        dependencies.username ?? env.USER ?? env.LOGNAME ?? "";
      if (!linger) {
        output.stdout(
          "The service starts when you log in. To start it at boot without logging in:\n"
            + "  phi service install --linger\n",
        );
        return 0;
      }
      const loginctl = which("loginctl");
      if (!loginctl || !username) {
        output.stdout(
          "Could not enable lingering. Run:\n  loginctl enable-linger $USER\n",
        );
        return 0;
      }
      const shown = await run(
        [loginctl, "show-user", username, "--property=Linger"],
        true,
      );
      if (shown.stdout.includes("Linger=yes")) return 0;
      const enabled = await run([loginctl, "enable-linger", username], true);
      if (enabled.exitCode === 0) {
        output.stdout("Linger enabled; the service will start at boot.\n");
        return 0;
      }
      output.stdout(
        "Could not enable lingering. Run:\n"
          + `  loginctl enable-linger ${username}\n`,
      );
      return 0;
    }

    if (subcommand === "uninstall") {
      requireInstalled();
      await run([systemctl, "--user", "disable", "--now", unit], true);
      unlinkSync(path);
      await run([systemctl, "--user", "daemon-reload"]);
      output.stdout("Uninstalled the Phi service.\n");
      return 0;
    }

    if (subcommand === "start" || subcommand === "stop" || subcommand === "restart") {
      requireInstalled();
      await run([systemctl, "--user", subcommand, unit]);
      const verb =
        subcommand === "start" ? "started"
        : subcommand === "stop" ? "stopped"
        : "restarted";
      output.stdout(`Phi service ${verb}.\n`);
      return 0;
    }

    if (subcommand === "status") {
      if (!existsSync(path)) {
        output.stdout("Phi service is not installed.\n");
        return 1;
      }
      const shown = await run([
        systemctl,
        "--user",
        "show",
        unit,
        "--property=ActiveState,MainPID,UnitFileState",
        "--no-pager",
      ]);
      const status = parseSystemctlShow(shown.stdout);
      if (status.failed) {
        output.stderr("Phi service failed.\n");
        output.stderr("See: journalctl --user -u phi.service\n");
        return 1;
      }
      if (!status.running) {
        output.stdout("Phi service is installed but not running.\n");
        return 1;
      }
      output.stdout(
        status.pid > 0
          ? `Phi service is running (pid ${status.pid}).\n`
          : "Phi service is running.\n",
      );
      return 0;
    }

    throw new Error(`unknown service command ${JSON.stringify(subcommand)}`);
  }

  const launchctl = which("launchctl") ?? "/bin/launchctl";
  const uid = dependencies.uid ?? process.getuid?.();
  if (uid === undefined) throw new Error("could not determine the current user id");
  const guiDomain = `gui/${uid}`;
  const userDomain = `user/${uid}`;
  const guiTarget = `${guiDomain}/${LAUNCHD_LABEL}`;
  const userTarget = `${userDomain}/${LAUNCHD_LABEL}`;

  const requireInstalled = () => {
    if (!existsSync(path)) throw notInstalledError();
  };

  const loadedTargets = async () => {
    const loaded: { domain: string; target: string; stdout: string }[] = [];
    for (const candidate of [
      { domain: guiDomain, target: guiTarget },
      { domain: userDomain, target: userTarget },
    ]) {
      const command = [launchctl, "print", candidate.target];
      const printed = await run(command, true);
      if (printed.exitCode === 0) {
        loaded.push({ ...candidate, stdout: printed.stdout });
        continue;
      }
      if (isLaunchctlMissing(printed)) continue;
      throw launchctlCommandError(command, printed);
    }
    return loaded;
  };

  const bootoutTarget = async (target: string) => {
    const command = [launchctl, "bootout", target];
    const result = await run(command, true);
    if (result.exitCode === 0 || isLaunchctlMissing(result)) return;
    throw launchctlCommandError(command, result);
  };

  const bootoutBoth = async () => {
    await bootoutTarget(guiTarget);
    await bootoutTarget(userTarget);
  };

  const preferredDomain = async () => {
    const command = [launchctl, "print", guiDomain];
    const gui = await run(command, true);
    if (gui.exitCode === 0) return guiDomain;
    if (isLaunchctlDomainMissing(gui)) return userDomain;
    throw launchctlCommandError(command, gui);
  };

  const bootstrapAndStart = async (domain: string) => {
    requireInstalled();
    const target = `${domain}/${LAUNCHD_LABEL}`;
    await run([launchctl, "bootstrap", domain, path]);
    await run([launchctl, "enable", target]);
    await run([launchctl, "kickstart", target]);
  };

  if (subcommand === "install") {
    writeDefinition(path, contents);
    if (input.logPath) mkdirSync(dirname(input.logPath), { recursive: true });
    await bootoutBoth();
    await bootstrapAndStart(await preferredDomain());
    output.stdout(`Installed and started the Phi service (${path}).\n`);
    output.stdout(`Open ${listenUrl(env)}\n`);
    return 0;
  }

  if (subcommand === "uninstall") {
    requireInstalled();
    await bootoutBoth();
    unlinkSync(path);
    output.stdout("Uninstalled the Phi service.\n");
    return 0;
  }

  if (subcommand === "start") {
    const loaded = await loadedTargets();
    if (loaded.length > 0) {
      const primary = loaded.find((entry) => entry.domain === guiDomain) ?? loaded[0]!;
      for (const extra of loaded) {
        if (extra.target !== primary.target) await bootoutTarget(extra.target);
      }
      await run([launchctl, "kickstart", primary.target]);
      output.stdout("Phi service started.\n");
      return 0;
    }
    await bootstrapAndStart(await preferredDomain());
    output.stdout("Phi service started.\n");
    return 0;
  }

  if (subcommand === "stop") {
    requireInstalled();
    await bootoutBoth();
    output.stdout("Phi service stopped.\n");
    return 0;
  }

  if (subcommand === "restart") {
    requireInstalled();
    await bootoutBoth();
    await bootstrapAndStart(await preferredDomain());
    output.stdout("Phi service restarted.\n");
    return 0;
  }

  if (subcommand === "status") {
    if (!existsSync(path)) {
      output.stdout("Phi service is not installed.\n");
      return 1;
    }
    const loaded = await loadedTargets();
    if (loaded.length === 0) {
      output.stdout("Phi service is installed but not running.\n");
      return 1;
    }
    const primary = loaded.find((entry) => entry.domain === guiDomain) ?? loaded[0]!;
    const status = parseLaunchctlPrint(primary.stdout);
    if (!status.running) {
      output.stdout("Phi service is installed but not running.\n");
      return 1;
    }
    output.stdout(
      status.pid > 0
        ? `Phi service is running (pid ${status.pid}).\n`
        : "Phi service is running.\n",
    );
    return 0;
  }

  throw new Error(`unknown service command ${JSON.stringify(subcommand)}`);
}
